export const APPLICATIONS_API_REQUEST="APPLICATIONS/API_REQUEST"
export const APPLICATIONS_API_SUCCESS="APPLICATIONS/API_SUCCESS"
export const APPLICATIONS_API_FAILED="APPLICATIONS/API_FAILED"

export const APPLICATIONS_SET_API_REQUEST="APPLICATIONS/API_SET_REQUEST"
export const APPLICATIONS_SET_API_SUCCESS="APPLICATIONS/API_SET_SUCCESS"
export const APPLICATIONS_SET_API_FAILED="APPLICATIONS/API_SET_FAILED"

export const SCOPES_API_REQUEST="APPLICATIONS/SCOPES_API_REQUEST"
export const SCOPES_API_SUCCESS="APPLICATIONS/SCOPES_API_SUCCESS"
export const SCOPES_API_FAILED="APPLICATIONS/SCOPES_API_FAILED"